---
- name: Get VM list
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Get VM list
      vmware_vm_facts:
        hostname: "{{ inventory_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
      register: VM_list
    - debug: var=VM_list